# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
# avoid duplicate tests in PRs
branches:
  only:
    - master
os:
  - linux
  - osx
julia:
  - 1.4
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
